---
extends: default

ignore: |
  .git/

rules:
  braces:
    forbid: false
    min-spaces-inside: 1
    max-spaces-inside: 1
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
  document-start: false
  indentation:
    spaces: 2
    indent-sequences: consistent
  line-length: disable
